// init/seed.js
require('dotenv').config();
const mongoose = require('mongoose');
const User = require('../models/user');
const bcrypt = require('bcrypt');

const MONGO_URI = process.env.MONGO_URI || "mongodb+srv://rohithkatika2_db_user:rohith8247203669@quick-teams.vqz7le3.mongodb.net/?retryWrites=true&w=majority&appName=quick-teams";

async function seed() {
  await mongoose.connect(MONGO_URI);

  console.log("Connected to DB... clearing old data...");
  await User.deleteMany({}); // clear users

  const hash = await bcrypt.hash("password123", 10);

  const users = [
    {
      name: "Arshad",
      email: "arshad@example.com",
      passwordHash: hash,
      skills: ["React", "Node.js"],
      needs: ["MongoDB", "UI Design"],
      availability: "Evenings",
    },
    {
      name: "Siddharth",
      email: "sid@example.com",
      passwordHash: hash,
      skills: ["MongoDB", "Express"],
      needs: ["React"],
      availability: "Weekends",
    },
    {
      name: "Ganesh",
      email: "ganesh@example.com",
      passwordHash: hash,
      skills: ["Python", "Machine Learning"],
      needs: ["Frontend"],
      availability: "Mornings",
    },
    {
      name: "Rohith",
      email: "rohith@example.com",
      passwordHash: hash,
      skills: ["UI/UX", "Bootstrap"],
      needs: ["Backend"],
      availability: "Anytime",
    },
    {
  name: "Aman",
  email: "aman@example.com",
  passwordHash: hash,
  skills: ["Java", "Spring Boot", "Hibernate", "SQL", "PostgreSQL", "Docker", "Kubernetes", "Microservices", "REST API"],
  needs: ["React", "UI/UX"],
  availability: "Afternoons",
},
{
  name: "Neha",
  email: "neha@example.com",
  passwordHash: hash,
  skills: ["C++", "DSA", "Algorithms", "Java", "Python", "GraphQL"],
  needs: ["MongoDB", "UI Design"],
  availability: "Evenings",
},
{
  name: "Kiran",
  email: "kiran@example.com",
  passwordHash: hash,
  skills: ["Python", "Flask", "Django", "Pandas", "NumPy", "Matplotlib", "AI/ML", "Deep Learning", "TensorFlow", "Keras", "NLP"],
  needs: ["React", "UI Design", "Backend"],
  availability: "Mornings",
},
{
  name: "Varun",
  email: "varun@example.com",
  passwordHash: hash,
  skills: ["JavaScript", "Next.js", "React", "Redux", "Node.js", "Express", "MongoDB", "Mongoose", "JWT Auth", "REST API"],
  needs: ["Database", "DevOps"],
  availability: "Weekends",
},
{
  name: "Meena",
  email: "meena@example.com",
  passwordHash: hash,
  skills: ["HTML", "CSS", "Bootstrap", "Tailwind", "Sass", "UI/UX", "Wireframing", "Figma", "Canva"],
  needs: ["Node.js"],
  availability: "Anytime",
},
{
  name: "Ravi",
  email: "ravi@example.com",
  passwordHash: hash,
  skills: ["Go", "Microservices", "Docker", "Kubernetes", "Cloud", "AWS", "Terraform", "CI/CD", "Monitoring", "Grafana", "Prometheus"],
  needs: ["Frontend"],
  availability: "Evenings",
},
{
  name: "Ishita",
  email: "ishita@example.com",
  passwordHash: hash,
  skills: ["Angular", "TypeScript", "RxJS", "NgRx", "HTML", "CSS", "Sass", "UI Testing", "Jest"],
  needs: ["MongoDB"],
  availability: "Afternoons",
},
{
  name: "Aditya",
  email: "aditya@example.com",
  passwordHash: hash,
  skills: ["Node.js", "Express", "MongoDB", "SQL", "PostgreSQL", "Redis", "WebSockets", "JWT", "GraphQL", "API Design"],
  needs: ["UI/UX"],
  availability: "Weekends",
},
{
  name: "Sneha",
  email: "sneha@example.com",
  passwordHash: hash,
  skills: ["Java", "Hibernate", "Spring Boot", "Spring Security", "JUnit", "Maven", "REST APIs"],
  needs: ["React", "Frontend"],
  availability: "Mornings",
},
{
  name: "Vikas",
  email: "vikas@example.com",
  passwordHash: hash,
  skills: ["Python", "Django", "FastAPI", "Flask", "Celery", "RabbitMQ", "Redis", "REST API", "SQLAlchemy"],
  needs: ["Frontend", "UI/UX"],
  availability: "Anytime",
},
{
  name: "Tanya",
  email: "tanya@example.com",
  passwordHash: hash,
  skills: ["C#", ".NET", "Entity Framework", "Azure", "SQL Server", "Microservices", "DevOps"],
  needs: ["Frontend"],
  availability: "Afternoons",
},
{
  name: "Dev",
  email: "dev@example.com",
  passwordHash: hash,
  skills: ["Flutter", "Dart", "Firebase", "Cloud Firestore", "Push Notifications", "UI Design", "Android Studio", "Xcode"],
  needs: ["Backend", "API"],
  availability: "Weekends",
},
{
  name: "Rhea",
  email: "rhea@example.com",
  passwordHash: hash,
  skills: ["iOS", "Swift", "SwiftUI", "Xcode", "UIKit", "Core Data", "ARKit", "Machine Learning"],
  needs: ["Backend"],
  availability: "Mornings",
},
{
  name: "Kabir",
  email: "kabir@example.com",
  passwordHash: hash,
  skills: ["Unity", "C#", "Game Development", "3D Models", "VR/AR", "Blender", "Graphics"],
  needs: ["AI/ML"],
  availability: "Evenings",
},
{
  name: "Sanya",
  email: "sanya@example.com",
  passwordHash: hash,
  skills: ["Data Science", "Python", "R", "Pandas", "NumPy", "Scikit-Learn", "Tableau", "PowerBI", "Data Visualization"],
  needs: ["Web Development"],
  availability: "Afternoons",
},
{
  name: "Harish",
  email: "harish@example.com",
  passwordHash: hash,
  skills: ["PHP", "Laravel", "MySQL", "jQuery", "REST API", "Vue.js", "Tailwind"],
  needs: ["DevOps"],
  availability: "Anytime",
},
{
  name: "Naina",
  email: "naina@example.com",
  passwordHash: hash,
  skills: ["Rust", "Systems Programming", "WebAssembly", "Concurrency", "Data Structures", "Algorithms"],
  needs: ["Frontend"],
  availability: "Mornings",
},
{
  name: "Anuj",
  email: "anuj@example.com",
  passwordHash: hash,
  skills: ["Blockchain", "Solidity", "Ethereum", "Smart Contracts", "Web3.js", "Truffle", "Hardhat"],
  needs: ["UI/UX"],
  availability: "Evenings",
},
{
  name: "Divya",
  email: "divya@example.com",
  passwordHash: hash,
  skills: ["Cybersecurity", "Pen Testing", "Kali Linux", "Burp Suite", "Wireshark", "OWASP", "Ethical Hacking"],
  needs: ["Backend"],
  availability: "Afternoons",
},
{
  name: "Rohil",
  email: "rohil@example.com",
  passwordHash: hash,
  skills: ["ML", "Deep Learning", "Pytorch", "TensorFlow", "NLP", "Computer Vision", "OpenCV", "Data Engineering", "ETL"],
  needs: ["Frontend"],
  availability: "Weekends",
},
{
  name: "Mitali",
  email: "mitali@example.com",
  passwordHash: hash,
  skills: ["HTML", "CSS", "Bootstrap", "JavaScript", "React", "Redux", "Node.js", "MongoDB", "Express", "REST API"],
  needs: ["Testing"],
  availability: "Evenings",
},
{
  name: "Saurav",
  email: "saurav@example.com",
  passwordHash: hash,
  skills: ["Python", "Data Science", "NumPy", "Pandas", "Matplotlib", "Seaborn", "Scikit-Learn", "ML Algorithms", "Data Visualization"],
  needs: ["Frontend"],
  availability: "Mornings",
},
{
  name: "Priya",
  email: "priya@example.com",
  passwordHash: hash,
  skills: ["Android", "Kotlin", "Java", "Firebase", "Retrofit", "Glide", "SQLite"],
  needs: ["Backend"],
  availability: "Afternoons",
},
{
  name: "Arjun",
  email: "arjun@example.com",
  passwordHash: hash,
  skills: ["Node.js", "Express", "NestJS", "TypeScript", "PostgreSQL", "GraphQL", "Prisma", "Redis"],
  needs: ["Frontend"],
  availability: "Weekends",
},
{
  name: "Komal",
  email: "komal@example.com",
  passwordHash: hash,
  skills: ["UI/UX", "Figma", "Adobe XD", "Wireframes", "Prototyping", "User Testing"],
  needs: ["Backend"],
  availability: "Anytime",
},
{
  name: "Yash",
  email: "yash@example.com",
  passwordHash: hash,
  skills: ["C", "C++", "Python", "Algorithms", "Data Structures", "Competitive Programming"],
  needs: ["Databases"],
  availability: "Afternoons",
},
{
  name: "Simran",
  email: "simran@example.com",
  passwordHash: hash,
  skills: ["React", "Next.js", "Tailwind", "Sass", "UI Libraries", "Storybook", "Testing Library"],
  needs: ["Backend"],
  availability: "Evenings",
},
{
  name: "Pankaj",
  email: "pankaj@example.com",
  passwordHash: hash,
  skills: ["Java", "Spring Boot", "Hibernate", "REST APIs", "MySQL", "Microservices", "Kafka"],
  needs: ["React"],
  availability: "Weekends",
},
{
  name: "Chitra",
  email: "chitra@example.com",
  passwordHash: hash,
  skills: ["Machine Learning", "Deep Learning", "TensorFlow", "Keras", "Computer Vision", "Image Processing", "NLP"],
  needs: ["Web Development"],
  availability: "Mornings",
},
{
  name: "Rohini",
  email: "rohini@example.com",
  passwordHash: hash,
  skills: ["PHP", "Laravel", "MySQL", "Vue.js", "Tailwind", "REST APIs"],
  needs: ["Testing"],
  availability: "Anytime",
},
{
  name: "Sandeep",
  email: "sandeep@example.com",
  passwordHash: hash,
  skills: ["Go", "Gin Framework", "PostgreSQL", "Docker", "Kubernetes", "Microservices", "CI/CD"],
  needs: ["Frontend"],
  availability: "Afternoons",
},
{
  name: "Aarti",
  email: "aarti@example.com",
  passwordHash: hash,
  skills: ["Ruby", "Rails", "PostgreSQL", "RSpec", "Capybara", "Heroku", "Stripe Integration"],
  needs: ["Frontend"],
  availability: "Mornings",
},
{
  name: "Tarun",
  email: "tarun@example.com",
  passwordHash: hash,
  skills: ["React Native", "JavaScript", "Redux", "Expo", "Firebase", "APIs"],
  needs: ["Backend"],
  availability: "Weekends",
},
{
  name: "Madhuri",
  email: "madhuri@example.com",
  passwordHash: hash,
  skills: ["C", "Embedded Systems", "IoT", "Arduino", "Raspberry Pi", "Sensors"],
  needs: ["Cloud"],
  availability: "Anytime",
},
{
  name: "Vivek",
  email: "vivek@example.com",
  passwordHash: hash,
  skills: ["Cloud Computing", "AWS", "Azure", "GCP", "Terraform", "Ansible", "CI/CD"],
  needs: ["Frontend"],
  availability: "Afternoons",
},
{
  name: "Isha",
  email: "isha@example.com",
  passwordHash: hash,
  skills: ["HTML", "CSS", "JavaScript", "Bootstrap", "React", "Redux", "Next.js", "Tailwind"],
  needs: ["Backend"],
  availability: "Evenings",
},
{
  name: "Raj",
  email: "raj@example.com",
  passwordHash: hash,
  skills: ["C++", "Python", "Machine Learning", "AI", "Data Structures", "Algorithms"],
  needs: ["Frontend"],
  availability: "Weekends",
},
{
  name: "Geeta",
  email: "geeta@example.com",
  passwordHash: hash,
  skills: ["Excel", "Tableau", "PowerBI", "SQL", "ETL", "Data Analysis"],
  needs: ["Web Development"],
  availability: "Mornings",
},
{
  name: "Farhan",
  email: "farhan@example.com",
  passwordHash: hash,
  skills: ["Blockchain", "Solidity", "Ethereum", "Hardhat", "Web3.js", "Metamask"],
  needs: ["UI/UX"],
  availability: "Afternoons",
},
{
  name: "Rekha",
  email: "rekha@example.com",
  passwordHash: hash,
  skills: ["Testing", "Manual Testing", "Selenium", "JUnit", "Postman", "API Testing"],
  needs: ["Backend"],
  availability: "Anytime",
},
{
  name: "Ankit",
  email: "ankit@example.com",
  passwordHash: hash,
  skills: ["Java", "Spring Boot", "JPA", "Hibernate", "MySQL", "REST APIs", "GraphQL"],
  needs: ["UI Design"],
  availability: "Evenings",
},
{
  name: "Shalini",
  email: "shalini@example.com",
  passwordHash: hash,
  skills: ["Python", "Flask", "Pandas", "Machine Learning", "Data Visualization"],
  needs: ["Frontend"],
  availability: "Weekends",
},
{
  name: "Hemant",
  email: "hemant@example.com",
  passwordHash: hash,
  skills: ["C", "C++", "Rust", "Assembly", "Linux Kernel", "Systems Programming"],
  needs: ["UI/UX"],
  availability: "Afternoons",
},
{
  name: "Pooja",
  email: "pooja@example.com",
  passwordHash: hash,
  skills: ["Figma", "UI/UX", "Wireframes", "Prototyping", "Mobile Design", "Responsive Design"],
  needs: ["Backend"],
  availability: "Mornings",
},
{
  name: "Manoj",
  email: "manoj@example.com",
  passwordHash: hash,
  skills: ["Node.js", "Express", "MongoDB", "Redis", "GraphQL", "Docker", "Kubernetes"],
  needs: ["Frontend"],
  availability: "Anytime",
},
{
  name: "Anita",
  email: "anita@example.com",
  passwordHash: hash,
  skills: ["Angular", "TypeScript", "RxJS", "NgRx", "REST APIs", "Firebase"],
  needs: ["Backend"],
  availability: "Afternoons",
},
{
  name: "Shubham",
  email: "shubham@example.com",
  passwordHash: hash,
  skills: ["Python", "TensorFlow", "Keras", "NLP", "Speech Recognition", "AI/ML"],
  needs: ["Frontend"],
  availability: "Evenings",
},
{
  name: "Deepa",
  email: "deepa@example.com",
  passwordHash: hash,
  skills: ["JavaScript", "Vue.js", "Nuxt.js", "Vuetify", "Tailwind", "Axios", "REST APIs"],
  needs: ["Backend"],
  availability: "Weekends",
},
{
  name: "Harsh",
  email: "harsh@example.com",
  passwordHash: hash,
  skills: ["DevOps", "CI/CD", "Jenkins", "Kubernetes", "AWS", "Terraform", "Monitoring"],
  needs: ["Frontend"],
  availability: "Mornings",
},
{
  name: "Leena",
  email: "leena@example.com",
  passwordHash: hash,
  skills: ["Content Writing", "SEO", "Digital Marketing", "Copywriting", "WordPress"],
  needs: ["Full-stack"],
  availability: "Anytime",
},
{
  name: "Dhruv",
  email: "dhruv@example.com",
  passwordHash: hash,
  skills: ["C#", ".NET Core", "Entity Framework", "SQL Server", "Azure", "REST API"],
  needs: ["Frontend"],
  availability: "Afternoons",
},
{
  name: "Pari",
  email: "pari@example.com",
  passwordHash: hash,
  skills: ["HTML", "CSS", "Sass", "Bootstrap", "JavaScript", "React", "Next.js", "Material UI"],
  needs: ["Backend"],
  availability: "Evenings",
},
{
  name: "Akash",
  email: "akash@example.com",
  passwordHash: hash,
  skills: ["Python", "ETL", "Big Data", "Hadoop", "Spark", "Kafka", "Data Pipelines"],
  needs: ["Frontend"],
  availability: "Weekends",
},
{
  name: "Kavita",
  email: "kavita@example.com",
  passwordHash: hash,
  skills: ["Java", "Spring Boot", "JPA", "Hibernate", "MySQL", "REST API", "Spring Security"],
  needs: ["UI/UX"],
  availability: "Anytime",
},
{
  name: "Omkar",
  email: "omkar@example.com",
  passwordHash: hash,
  skills: ["Go", "Fiber", "PostgreSQL", "Docker", "Kubernetes", "Cloud"],
  needs: ["Frontend"],
  availability: "Afternoons",
},
{
  name: "Zoya",
  email: "zoya@example.com",
  passwordHash: hash,
  skills: ["JavaScript", "Node.js", "Express", "React", "Redux", "MongoDB", "GraphQL"],
  needs: ["UI Design"],
  availability: "Evenings",
},
{
  name: "Mohan",
  email: "mohan@example.com",
  passwordHash: hash,
  skills: ["Python", "FastAPI", "Pydantic", "SQLAlchemy", "PostgreSQL", "Docker", "JWT"],
  needs: ["Frontend"],
  availability: "Weekends",
},
{
  name: "Lavanya",
  email: "lavanya@example.com",
  passwordHash: hash,
  skills: ["UX Design", "Figma", "Adobe XD", "Prototyping", "Mobile Design"],
  needs: ["Backend"],
  availability: "Mornings",
},
{
  name: "Nikhil",
  email: "nikhil@example.com",
  passwordHash: hash,
  skills: ["React", "Redux", "Next.js", "Tailwind", "REST API", "GraphQL"],
  needs: ["Databases"],
  availability: "Anytime",
},
{
  name: "Seema",
  email: "seema@example.com",
  passwordHash: hash,
  skills: ["Testing", "Selenium", "JUnit", "Postman", "Cypress", "Mocha", "Chai"],
  needs: ["Backend"],
  availability: "Afternoons",
},
{
  name: "Jay",
  email: "jay@example.com",
  passwordHash: hash,
  skills: ["Node.js", "Express", "MongoDB", "JWT", "GraphQL", "WebSockets", "Redis"],
  needs: ["UI/UX"],
  availability: "Mornings",
},
{
  name: "Alisha",
  email: "alisha@example.com",
  passwordHash: hash,
  skills: ["Java", "Spring Boot", "Microservices", "Docker", "Kubernetes", "MySQL"],
  needs: ["Frontend"],
  availability: "Evenings",
},



  ];

  await User.insertMany(users);
  console.log("✅ Users seeded!");

  mongoose.disconnect();
}

seed();